import { IncomingCategoryItem } from './types';

export const INCOMING_CATEGORIES: IncomingCategoryItem[] = [
  {
    id: 'cat-raw-material',
    name: 'Raw Material',
    code: 'IN-RM',
    description: 'Incoming sheet metals, alloy bars, extruded aluminum, copper coils, and raw polymers.',
    itemCount: 42,
    pendingLots: 4,
    passRate: 98.9,
    sampleItems: ['Alloy 6061-T6 Extrusion Bar', 'Cold-Rolled Steel Sheet 2.0mm', 'High Conductivity Copper Coil', 'Engineered Polycarbonate Pellets'],
    inspectionStandard: 'ISO 2859-1 Level II / ASTM E8',
    supplierCount: 6,
    tag: 'Metals & Polymers',
  },
  {
    id: 'cat-led',
    name: 'LED',
    code: 'IN-LED',
    description: 'SMD LED chipsets, COB arrays, optical diodes, luminous flux ratings, and CCT binning.',
    itemCount: 28,
    pendingLots: 3,
    passRate: 99.4,
    sampleItems: ['SMD 2835 High-CRI 4000K', 'COB Matrix Array 50W', 'Side-View Indicator LEDs', 'UV Optical Inspection Diodes'],
    inspectionStandard: 'IEC 62471 / ANSI C78.377',
    supplierCount: 4,
    tag: 'Optoelectronics',
  },
  {
    id: 'cat-fan',
    name: 'Fan',
    code: 'IN-FAN',
    description: 'Brushless DC cooling fans, axial impeller assemblies, static pressure, dynamic balance & RPM.',
    itemCount: 19,
    pendingLots: 2,
    passRate: 97.8,
    sampleItems: ['120mm Dual Ball Bearing Fan 24V', '80mm PWM High-Static Blower', '40mm Micro Server Cooling Fan', 'Frameless Impeller Assembly'],
    inspectionStandard: 'AMCA 210 / ISO 5801',
    supplierCount: 3,
    tag: 'Thermal & Airflow',
  },
  {
    id: 'cat-protection',
    name: 'Protection',
    code: 'IN-PROT',
    description: 'Metal oxide varistors (MOV), thermal fuses, ceramic cartridge fuses, TVS diodes, and ESD barriers.',
    itemCount: 31,
    pendingLots: 1,
    passRate: 100.0,
    sampleItems: ['14D471K Metal Oxide Varistor', 'Fast-Blow Ceramic Fuse 10A 250V', 'Thermal Cutoff Switch 130°C', 'Bidirectional TVS Diode 15V'],
    inspectionStandard: 'IEC 61000-4-5 / UL 1449 4th Ed.',
    supplierCount: 5,
    tag: 'Safety & Circuit Guard',
  },
  {
    id: 'cat-subcontractor-sf',
    name: 'Subcontractor SF',
    code: 'IN-SUB-SF',
    description: 'Semi-finished outsourced components: SMT soldered sub-boards, stamped chassis, and blank CNC gears.',
    itemCount: 37,
    pendingLots: 5,
    passRate: 96.5,
    sampleItems: ['SMT Sensor Pre-Assembly Board', 'Progressive Die Stamped Case', 'CNC Turned Input Shaft Blank', 'Pre-Coated Heatsink Core'],
    inspectionStandard: 'IPC-A-610 Class 3 / ISO 9001',
    supplierCount: 7,
    tag: 'Semi-Finished Outsourced',
  },
  {
    id: 'cat-subcontractor-fg',
    name: 'Subcontractor FG',
    code: 'IN-SUB-FG',
    description: 'Finished outsourced assemblies, turn-key modules, programmed controllers, and partner products.',
    itemCount: 22,
    pendingLots: 2,
    passRate: 99.2,
    sampleItems: ['Integrated Microcontroller Hub', 'Sealed Power Supply Unit 400W', 'Keypad Display Module FG', 'Calibrated Optical Head'],
    inspectionStandard: 'MIL-STD-105E Normal / ISO 13485',
    supplierCount: 4,
    tag: 'Finished Turn-Key Goods',
  },
  {
    id: 'cat-packing-items',
    name: 'Packing Items',
    code: 'IN-PACK',
    description: 'Double-wall corrugated shipping boxes, ESD antistatic bubble rolls, serialized barcode labels, cushions.',
    itemCount: 25,
    pendingLots: 3,
    passRate: 99.8,
    sampleItems: ['5-Ply Heavy Duty Master Carton', 'Shielding Antistatic Bags 300x400', 'Thermal Transfer Label Stock 4x6', 'Form-Fitting EPE Foam Inserts'],
    inspectionStandard: 'ISTA 1A Drop / FEFCO 0201',
    supplierCount: 3,
    tag: 'Packaging & Labels',
  },
  {
    id: 'cat-others',
    name: 'Others',
    code: 'IN-OTH',
    description: 'Industrial fasteners, silicone potting compound, threadlockers, neoprene gaskets, O-rings & consumables.',
    itemCount: 34,
    pendingLots: 2,
    passRate: 98.1,
    sampleItems: ['M4 Stainless Steel Torx Screws', 'Thermal Conductive Silicone Gel', 'Medium Strength Threadlocker Blue', 'Fluorocarbon High-Temp O-Ring'],
    inspectionStandard: 'DIN 912 / ISO 4762 / RoHS 3',
    supplierCount: 8,
    tag: 'Fasteners & Chemicals',
  },
];

export interface IncomingSampleLot {
  id: string;
  lotNumber: string;
  category: string;
  partNumber: string;
  partName: string;
  supplier: string;
  quantity: number;
  unit: string;
  nominalSpec: string;
  measuredSpec: string;
  status: 'pass' | 'fail' | 'pending';
  receivedDate: string;
}

export const SAMPLE_INCOMING_LOTS: IncomingSampleLot[] = [
  // Raw Material
  {
    id: 'LOT-IN-101',
    lotNumber: 'LOT-RM-2026-0041',
    category: 'Raw Material',
    partNumber: 'AL-6061-BAR-50',
    partName: 'Alloy 6061-T6 Extrusion Bar',
    supplier: 'Alcoa Precision Metals',
    quantity: 1200,
    unit: 'kg',
    nominalSpec: '50.00 ± 0.05 mm dia',
    measuredSpec: '50.02 mm (Spectro OK)',
    status: 'pass',
    receivedDate: '2026-09-08 08:30',
  },
  {
    id: 'LOT-IN-102',
    lotNumber: 'LOT-RM-2026-0042',
    category: 'Raw Material',
    partNumber: 'CR-STEEL-2MM',
    partName: 'Cold-Rolled Steel Sheet 2.0mm',
    supplier: 'Nippon Steel Corp',
    quantity: 850,
    unit: 'sheets',
    nominalSpec: '2.00 ± 0.03 mm thk',
    measuredSpec: 'Pending Micrometer Gauge',
    status: 'pending',
    receivedDate: '2026-09-09 07:15',
  },
  // LED
  {
    id: 'LOT-IN-201',
    lotNumber: 'LOT-LED-2026-0104',
    category: 'LED',
    partNumber: 'SMD-2835-4000K',
    partName: 'SMD 2835 High-CRI 4000K LED',
    supplier: 'Lumileds Enterprise',
    quantity: 50000,
    unit: 'pcs',
    nominalSpec: '65 lm @ 60mA, CRI > 90',
    measuredSpec: '66.4 lm, CRI 92.1 (Bin 4A)',
    status: 'pass',
    receivedDate: '2026-09-08 11:20',
  },
  {
    id: 'LOT-IN-202',
    lotNumber: 'LOT-LED-2026-0105',
    category: 'LED',
    partNumber: 'COB-50W-V2',
    partName: 'COB Matrix Array 50W',
    supplier: 'Nichia Opto Tech',
    quantity: 2400,
    unit: 'pcs',
    nominalSpec: '36.0V ± 1.2V @ 1400mA',
    measuredSpec: 'Spectrometer Check in progress',
    status: 'pending',
    receivedDate: '2026-09-09 09:00',
  },
  // Fan
  {
    id: 'LOT-IN-301',
    lotNumber: 'LOT-FAN-2026-0088',
    category: 'Fan',
    partNumber: 'FAN-DC-120-24V',
    partName: '120mm Dual Ball Bearing Fan',
    supplier: 'Delta Electronics',
    quantity: 1500,
    unit: 'units',
    nominalSpec: '3200 ± 10% RPM, < 38 dBA',
    measuredSpec: '3180 RPM, 35.6 dBA',
    status: 'pass',
    receivedDate: '2026-09-07 14:00',
  },
  // Protection
  {
    id: 'LOT-IN-401',
    lotNumber: 'LOT-PROT-2026-0210',
    category: 'Protection',
    partNumber: 'MOV-14D471K',
    partName: '14D471K Metal Oxide Varistor',
    supplier: 'Littelfuse Global',
    quantity: 10000,
    unit: 'pcs',
    nominalSpec: '470V ± 10% Clamping',
    measuredSpec: '468.2V Varistor Voltage',
    status: 'pass',
    receivedDate: '2026-09-08 16:45',
  },
  // Subcontractor SF
  {
    id: 'LOT-IN-501',
    lotNumber: 'LOT-SUB-SF-2026-0315',
    category: 'Subcontractor SF',
    partNumber: 'PCB-SMT-SENSOR-V4',
    partName: 'SMT Sensor Pre-Assembly Board',
    supplier: 'Apex SMT Outsourcing',
    quantity: 3200,
    unit: 'boards',
    nominalSpec: 'AOI solder fillet > 85%',
    measuredSpec: 'AOI scan passed 100% IPC-A-610',
    status: 'pass',
    receivedDate: '2026-09-08 10:10',
  },
  // Subcontractor FG
  {
    id: 'LOT-IN-601',
    lotNumber: 'LOT-SUB-FG-2026-0180',
    category: 'Subcontractor FG',
    partNumber: 'PSU-400W-SEALED',
    partName: 'Sealed Power Supply Unit 400W',
    supplier: 'Fox-Tech Assemblies',
    quantity: 600,
    unit: 'units',
    nominalSpec: 'Hi-Pot 1500VAC, 12V ± 0.2V',
    measuredSpec: 'Dielectric OK, 12.04V ripple < 20mV',
    status: 'pass',
    receivedDate: '2026-09-07 17:30',
  },
  // Packing Items
  {
    id: 'LOT-IN-701',
    lotNumber: 'LOT-PACK-2026-0501',
    category: 'Packing Items',
    partNumber: 'BOX-5PLY-40X30X20',
    partName: '5-Ply Heavy Duty Master Carton',
    supplier: 'Smurfit Westrock',
    quantity: 5000,
    unit: 'pcs',
    nominalSpec: 'ECT > 44 lbs/in, Mullen 275 psi',
    measuredSpec: 'ECT 48.2 lbs/in, Burst passed',
    status: 'pass',
    receivedDate: '2026-09-08 13:15',
  },
  // Others
  {
    id: 'LOT-IN-801',
    lotNumber: 'LOT-OTH-2026-0612',
    category: 'Others',
    partNumber: 'SCR-M4X12-TORX',
    partName: 'M4 Stainless Steel Torx Screws',
    supplier: 'McMaster-Carr Supply',
    quantity: 40000,
    unit: 'pcs',
    nominalSpec: 'Torque rating > 4.2 N·m',
    measuredSpec: 'Breaking torque 5.8 N·m',
    status: 'pass',
    receivedDate: '2026-09-07 15:40',
  },
];
