import { InspectionRecord, SpecificationItem, AdminUser, DefectMetric } from './types';

export const INITIAL_INSPECTIONS: InspectionRecord[] = [
  {
    id: 'INS-9041',
    lotNumber: 'LOT-2026-8941',
    batchId: 'B-7720',
    partNumber: 'AL-6061-T6-PIN',
    partName: 'Aircraft Pivot Pin Assembly',
    module: 'incoming',
    supplierOrLine: 'Alcoa Precision Metals',
    nominalValue: 45.00,
    toleranceMin: 44.95,
    toleranceMax: 45.05,
    measuredValue: 45.02,
    unit: 'mm',
    status: 'pass',
    defectSeverity: 'none',
    inspectorId: 'QA-8941',
    inspectorName: 'Marcus Vance',
    timestamp: '2026-09-07 07:45:12',
    notes: 'Material test certificate verified. Laser micrometer within tolerance.',
    verifiedBy: 'Lead AD-1004',
  },
  {
    id: 'INS-9042',
    lotNumber: 'LOT-2026-8942',
    batchId: 'B-7721',
    partNumber: 'BRG-SKF-6204',
    partName: 'Sealed Deep Groove Ball Bearing',
    module: 'incoming',
    supplierOrLine: 'SKF Global Supply',
    nominalValue: 20.00,
    toleranceMin: 19.98,
    toleranceMax: 20.02,
    measuredValue: 20.01,
    unit: 'mm',
    status: 'pass',
    defectSeverity: 'none',
    inspectorId: 'QA-8941',
    inspectorName: 'Marcus Vance',
    timestamp: '2026-09-07 08:02:44',
    notes: 'Radial runout test passed with 0.004mm vibration spec.',
    verifiedBy: 'Lead AD-1004',
  },
  {
    id: 'INS-9043',
    lotNumber: 'LOT-2026-8943',
    batchId: 'B-7722',
    partNumber: 'FST-M8-125-88',
    partName: 'Grade 8.8 Hex Flange Bolt',
    module: 'incoming',
    supplierOrLine: 'Titan Fastener Logistics',
    nominalValue: 8.00,
    toleranceMin: 7.92,
    toleranceMax: 8.04,
    measuredValue: 8.16,
    unit: 'mm',
    status: 'fail',
    defectType: 'Thread Pitch Oversize',
    defectSeverity: 'critical',
    inspectorId: 'QA-8941',
    inspectorName: 'Marcus Vance',
    timestamp: '2026-09-07 08:15:30',
    notes: 'Thread gauge no-go test failed. Batch quarantined in Bay C-4.',
  },
  {
    id: 'INS-9044',
    lotNumber: 'LOT-2026-8944',
    batchId: 'B-8830',
    partNumber: 'CNC-SPN-HSG',
    partName: 'High-Speed CNC Spindle Housing',
    module: 'in-process',
    supplierOrLine: 'Line 3 - 5-Axis Milling Cell',
    nominalValue: 120.00,
    toleranceMin: 119.98,
    toleranceMax: 120.02,
    measuredValue: 120.005,
    unit: 'mm',
    status: 'pass',
    defectSeverity: 'none',
    inspectorId: 'QA-8941',
    inspectorName: 'Marcus Vance',
    timestamp: '2026-09-07 08:22:19',
    notes: 'CMM automatic coordinate measurement completed without deviations.',
    verifiedBy: 'Lead AD-1004',
  },
  {
    id: 'INS-9045',
    lotNumber: 'LOT-2026-8945',
    batchId: 'B-8831',
    partNumber: 'ENG-BLK-BORE',
    partName: 'Cylinder Bore Concentricity Check',
    module: 'in-process',
    supplierOrLine: 'Line 2 - Honing & Finishing',
    nominalValue: 85.50,
    toleranceMin: 85.48,
    toleranceMax: 85.52,
    measuredValue: 85.47,
    unit: 'mm',
    status: 'fail',
    defectType: 'Undersized Bore Taper',
    defectSeverity: 'major',
    inspectorId: 'QA-8941',
    inspectorName: 'Marcus Vance',
    timestamp: '2026-09-07 08:34:02',
    notes: 'Bore gauge showed -0.03mm below specification. Tool offset adjusted.',
  },
  {
    id: 'INS-9046',
    lotNumber: 'LOT-2026-8946',
    batchId: 'B-8832',
    partNumber: 'PCB-SLD-SMT',
    partName: 'ECU Motherboard Solder Paste Thickness',
    module: 'in-process',
    supplierOrLine: 'Line 5 - Surface Mount Cell',
    nominalValue: 130.00,
    toleranceMin: 115.00,
    toleranceMax: 145.00,
    measuredValue: 128.50,
    unit: 'µm',
    status: 'pass',
    defectSeverity: 'none',
    inspectorId: 'QA-7112',
    inspectorName: 'Sarah Jenkins',
    timestamp: '2026-09-07 08:40:11',
    notes: '3D SPI camera optical check passed with zero bridging.',
  },
  {
    id: 'INS-9047',
    lotNumber: 'LOT-2026-8947',
    batchId: 'B-9010',
    partNumber: 'ANOD-SRF-PLT',
    partName: 'Mil-Spec Hard Anodized Coating',
    module: 'subcontracting',
    supplierOrLine: 'Apex Electroplating Subcontractor',
    nominalValue: 50.00,
    toleranceMin: 45.00,
    toleranceMax: 55.00,
    measuredValue: 48.20,
    unit: 'µm',
    status: 'pass',
    defectSeverity: 'none',
    inspectorId: 'QA-8941',
    inspectorName: 'Marcus Vance',
    timestamp: '2026-09-07 08:48:50',
    notes: 'Eddy-current coating thickness gauge verified across 12 test points.',
  },
  {
    id: 'INS-9048',
    lotNumber: 'LOT-2026-8948',
    batchId: 'B-9011',
    partNumber: 'HT-QNCH-HRD',
    partName: 'Induction Hardened Shaft Core',
    module: 'subcontracting',
    supplierOrLine: 'ThermalTech Metallurgy Ltd',
    nominalValue: 58.00,
    toleranceMin: 56.00,
    toleranceMax: 60.00,
    measuredValue: 57.50,
    unit: 'HRC',
    status: 'pending',
    defectSeverity: 'minor',
    inspectorId: 'QA-8941',
    inspectorName: 'Marcus Vance',
    timestamp: '2026-09-07 08:55:00',
    notes: 'Rockwell C test awaiting secondary micro-hardness metallography coupon.',
  },
  {
    id: 'INS-9049',
    lotNumber: 'LOT-2026-8949',
    batchId: 'B-9012',
    partNumber: 'STMP-BRKT-SUB',
    partName: 'Stamped Chassis Reinforcement Bracket',
    module: 'subcontracting',
    supplierOrLine: 'FormCraft Stamping Co',
    nominalValue: 3.20,
    toleranceMin: 3.10,
    toleranceMax: 3.30,
    measuredValue: 3.02,
    unit: 'mm',
    status: 'fail',
    defectType: 'Edge Burr Exceeds Spec',
    defectSeverity: 'major',
    inspectorId: 'QA-7112',
    inspectorName: 'Sarah Jenkins',
    timestamp: '2026-09-07 09:05:14',
    notes: 'Burr height measured 0.18mm (max allowed 0.05mm). Return to vendor requested.',
  }
];

export const INITIAL_SPECS: SpecificationItem[] = [
  {
    id: 'SPEC-101',
    partCode: 'AL-6061-T6-PIN',
    partName: 'Aircraft Pivot Pin Assembly',
    parameter: 'Outer Diameter',
    nominal: 45.00,
    tolerance: 0.05,
    unit: 'mm',
    revision: 'Rev C.2',
    category: 'Mechanical',
    status: 'Active',
    updatedAt: '2026-08-14'
  },
  {
    id: 'SPEC-102',
    partCode: 'BRG-SKF-6204',
    partName: 'Sealed Deep Groove Ball Bearing',
    parameter: 'Bore Inner Diameter',
    nominal: 20.00,
    tolerance: 0.02,
    unit: 'mm',
    revision: 'Rev B.1',
    category: 'Mechanical',
    status: 'Active',
    updatedAt: '2026-08-20'
  },
  {
    id: 'SPEC-103',
    partCode: 'FST-M8-125-88',
    partName: 'Grade 8.8 Hex Flange Bolt',
    parameter: 'Major Thread Diameter',
    nominal: 8.00,
    tolerance: 0.08,
    unit: 'mm',
    revision: 'Rev A.4',
    category: 'Mechanical',
    status: 'Active',
    updatedAt: '2026-07-29'
  },
  {
    id: 'SPEC-104',
    partCode: 'CNC-SPN-HSG',
    partName: 'High-Speed CNC Spindle Housing',
    parameter: 'Journal Runout Tolerance',
    nominal: 120.00,
    tolerance: 0.02,
    unit: 'mm',
    revision: 'Rev D.0',
    category: 'Mechanical',
    status: 'Active',
    updatedAt: '2026-08-30'
  },
  {
    id: 'SPEC-105',
    partCode: 'ANOD-SRF-PLT',
    partName: 'Mil-Spec Hard Anodized Coating',
    parameter: 'Dielectric Coating Depth',
    nominal: 50.00,
    tolerance: 5.00,
    unit: 'µm',
    revision: 'Rev C.1',
    category: 'Surface Finish',
    status: 'Active',
    updatedAt: '2026-09-01'
  }
];

export const INITIAL_ADMIN_USERS: AdminUser[] = [
  {
    id: 'USR-01',
    name: 'David Sterling',
    email: 'd.sterling@abccompany.com',
    role: 'System Admin',
    badgeId: 'AD-1004',
    department: 'Quality Engineering & Systems',
    activeShift: 'Shift A (Morning)',
    status: 'Online'
  },
  {
    id: 'USR-02',
    name: 'Marcus Vance',
    email: 'm.vance@abccompany.com',
    role: 'Senior Inspector',
    badgeId: 'QA-8941',
    department: 'Metrology & Incoming QA',
    activeShift: 'Shift A (Morning)',
    status: 'Online'
  },
  {
    id: 'USR-03',
    name: 'Sarah Jenkins',
    email: 's.jenkins@abccompany.com',
    role: 'Line Auditor',
    badgeId: 'QA-7112',
    department: 'In-Process Line 2 & 5',
    activeShift: 'Shift A (Morning)',
    status: 'On Line Audit'
  },
  {
    id: 'USR-04',
    name: 'Elena Rostova',
    email: 'e.rostova@abccompany.com',
    role: 'QA Lead',
    badgeId: 'QA-6500',
    department: 'Supplier Quality Assurance',
    activeShift: 'Shift B (Evening)',
    status: 'Offline'
  }
];

export const INITIAL_DEFECT_METRICS: DefectMetric[] = [
  { category: 'Dimensional Tolerance Breach', count: 18, percentage: 41.8, severity: 'major' },
  { category: 'Surface Finish / Burr Defect', count: 12, percentage: 27.9, severity: 'minor' },
  { category: 'Thread Pitch & Form Out of Spec', count: 8, percentage: 18.6, severity: 'critical' },
  { category: 'Tensile / Hardness Non-conformance', count: 5, percentage: 11.7, severity: 'major' }
];
